config/routes.rb
Rails.application.routes.draw do
  devise_for :models
  resources:messages
  root 'messages#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
belongs_to:model
end

app/models/model.rb
class Model < ApplicationRecord
	has_many :messages
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :find_message, only: [:show,:edit,:update,:destroy]
 def index
 	@messages=Message.all.order("created_at DESC")
 end

def destroy
	@message.destroy
	redirect_to root_path
end

def edit
end

def update
	if @message.update(message_params)
		redirect_to message_path
	else 
		render 'edit'
	end
end

 def new
 	@message=current_model.messages.build
 end

 def show
 end

 def create
 	@message=current_model.messages.build(message_params)
 	if @message.save
 		redirect_to root_path
 	else
 		render 'new'
 	end
 end

private 
	def message_params
		params.require(:message).permit(:title,:description)
	end
	def find_message
		@message=Message.find(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <body>
  	<div class="navbar navbar-default">
  		<div class="container">
  		
  			<div class="navbar-header">
  				<%=link_to "Message board",root_path, class:"navbar-brand"=%>
  			</div>

  			<ul class="nav navbar-nav">
  				<li><%=link_to "sign up",new_model_registration_path=%></li>
  					<%if model_signed_in?%>
  						<li><%=button_to "Sign out",destroy_model_session_path,method: :delete=%></li>
  					<%else%>
  						<li><%=link_to "log in",new_model_session_path=%> </li>
  					<%end%>
  			</ul>
  		<%if model_signed_in?%>
  			<p><%=link_to "new message",new_message_path ,class:"navbar-right navbar-text navbar-link"=%></p>
  		<<% end %>
  		</div>
  	</div>

  	  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>
    <%= yield %>
  
  </body>
</html>

app/views/messages/_form.html.erb
<%= simple_form_for @message do |f| %>
  <%= f.input :title ,label:"Enter message title"%>
  <%= f.input :description %>
  <%= f.button :submit %>
<% end %>

app/views/messages/edit.html.erb
<h1>Edit this message</h1>
<%= render 'form'%>
 <%= link_to "back",message_path,class: "btn btn-default" %>

app/views/messages/index.html.erb
<% @messages.each do |message|%>
 <h1> <%= message.title %> </h1>
 <h2> <%= link_to "view message",message_path(message),class: "btn btn-default " %> </h2>
<% end %>

<%= link_to "New message" ,new_message_path %>

app/views/messages/new.html.erb
<h1>
	new message
</h1>

<%= render 'form' =%>
<%= link_to "Back",root_path,class: "btn btn-default"=%>

app/views/messages/show.html.erb
 <h1> <%= @message.title %> </h1>
 <h2> <%= @message.description%> </h2>
<%= link_to "Back",root_path,class: "btn btn-default"=%>
 <%= link_to "Edit",edit_message_path(@message),class: "btn btn-default" %>
 <%= button_to "Delete", message_path(@message),method: :delete, data: { confirm:"Are you sure?" } =%>